### ISSUE TITLE
Rendering tag in `as` syntax (0.2.1)

### ISSUE THREAD

**Issue by spinus** [noirbizarre/django-absolute#3]
```
These template tags have exactly the same syntax as url.
```

That is not exactly true. When you are using {% url .... as variable %} the 'content' is not rendered, but in absolute is.

**Comment by noirbizarre** [comment]
You're right.
I'm going to fix this as soon as possible.

**Comment by spinus** [comment]
That was pretty quick, thanks.

**Comment by Elijen** [comment]
It seems like the fix works just for the first call of the tag. Not in a loop:

```
{% for post in posts %}
    {% url 'detail' hash=post.hash as detail_url %}
    {% absolute 'detail' hash=post.hash as absolute_detail_url %}
{% endfor %}
```

The first link is never rendered. The second one is rendered after the first loop.
